name: specreduce-dev
channels:
  - conda-forge
dependencies:
  - astropy
  - gwcs
  - numpy
  - scipy
  - specutils
  - matplotlib
  - pytest-astropy
  - photutils
  - tox
  - sphinx-astropy
  - sphinx-copybutton
  - sphinx-design
  - nbsphinx
  - pydata-sphinx-theme
  - synphot
